language: rust
cache: cargo
sudo: false
rust:
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
matrix:
  allow_failures:
  - rust: nightly
  fast_finish: true
  include:
  - rust: stable
    script:
    - rustup component add rustfmt-preview
    - cargo fmt --all -- --check