language: rust
cache: cargo
before_install:
  - sudo add-apt-repository universe
  - sudo apt-get -qq update
env:
  - TEST_COMMAND="cargo install rustfmt-nightly --force && cargo fmt --all -- --check"
  - TEST_COMMAND="cargo build --verbose --all"
  - TEST_COMMAND="cargo test --verbose --all" RUST_TEST_THREADS=1
rust:
  - stable
  - beta
  - nightly
script:
  - (eval "$TEST_COMMAND")
matrix:
  exclude:
  - rust: stable
    env: TEST_COMMAND="cargo install rustfmt-nightly --force && cargo fmt --all -- --check"
  - rust: beta
    env: TEST_COMMAND="cargo install rustfmt-nightly --force && cargo fmt --all -- --check"